# Generated by Django 2.2.6 on 2019-10-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(blank=True, max_length=2000)),
                ('id_marcador', models.IntegerField()),
                ('path_modelo', models.CharField(blank=True, max_length=2000)),
            ],
        ),
    ]
