# Generated by Django 2.2.6 on 2019-10-30 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ra', '0002_auto_20191029_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='objeto',
            old_name='path_modelo_OBJ',
            new_name='name_MTL',
        ),
        migrations.RenameField(
            model_name='objeto',
            old_name='path_modelo_MTL',
            new_name='name_OBJ',
        ),
        migrations.AddField(
            model_name='objeto',
            name='path_modelos',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
